config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_params, only: [:index,:create,:new,:update,:edit,:show]
  def index
    redirect_to new_post_comment_path
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.save
    redirect_to post_path(@post)
  end

  def show
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

private
  def set_params
    @post = Post.find(params[:post_id])
  end
  def comment_params
    params.require(:comment).permit(:name,:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_params, only: [:show, :update, :edit, :destroy]
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to posts_path
  end

  def show
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

private
  def set_params
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name,:subject,:category,:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= bootstrap_form_for ([@post,@post.comments.build]) do |f| %>

<%= f.text_field :name %>


<br />

<%= f.text_area :content %>

<%= f.submit %>
<% end %>

<%= link_to 'Go back', post_path(@post), class: "btn btn-default" %>

app/views/comments/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Edit your comment</h1>

<%= bootstrap_form_for ([@post,@comment]) do |f| %>

<%= f.text_field :name %>
<br />

<%= f.text_area :content %>

<%= f.submit %>
<% end %>


<%= link_to 'Go back', post_path(@post), class: "btn btn-default"%>

app/views/comments/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Add your comment here</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comment#update</h1>
<p>Find me in app/views/comment/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emergency</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>

  <body class="container-fluid">
    <header class="row banner">
      <section class="text-header">
        Post your emergencies here!
      </section>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1>Post your emergency!</h1>
<%= bootstrap_form_for @post do |f| %>

<%= f.text_field :name %>
<br />
<%= f.text_field :subject %>
<br />
<%= f.select :category, ['Latest News','Resources','Need HELP NOW'] %>
<br />
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

<%= link_to 'Go back', posts_path, class: "btn btn-default" %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit your post here</h1>

<%= bootstrap_form_for @post do |f| %>

<%= f.text_field :name %>
<br />
<%= f.text_field :subject %>
<br />
<%= f.select :category, ['Latest News','Resources','Need HELP NOW'] %>
<br />
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

<%= link_to 'Go back', posts_path, class: "btn btn-default" %>

app/views/posts/index.html.erb
<section class="container button-post">
    <%= link_to 'Post your emergency here', new_post_path,class: "btn btn-default btn-post" %>
</section>
<% @post.each do |post| %>
<section class="post-subject">
    <%= post.subject %>
</section>
<p> Posted on <%= post.created_at.strftime("%m:%d:%Y") %> at <%=post.created_at.strftime("%T") %></p>
<section class="post-name">
    Written by:
    <%= post.name %>
</section>
<section class="post-category">
    Category:
    <%= post.category %>
</section>
<br />
<section class="post-content">
    <%= post.content %>
</section>
<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
<%= link_to 'Comments', post_path(post) %>
<span>&nbsp&nbsp&nbsp</span>
<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
<%= link_to 'Edit', edit_post_path(post) %>
<span>&nbsp&nbsp&nbsp</span>
<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
<%= link_to 'Delete', post, method: :delete, data: {confirm: "Are you sure?"} %>
<hr/>

<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<section class="container button-post">
    <%= link_to 'Post your emergency here', new_post_path,class: "btn btn-default btn-post" %>
</section>
<section class="post-subject">
  <%= @post.subject %>
</section>
<p> Posted on <%= @post.created_at.strftime("%m:%d:%Y") %> at <%=@post.created_at.strftime("%T") %></p>
<section class="post-name">
    Written by:
    <%= @post.name %>
</section>

<section class="post-category">
    Category:
    <%= @post.category %>
</section>
<br />
<section class="post-content">
    <%= @post.content %>
</section>
<br />
<hr />
<h4>Comments</h4>
<% @post.comments.each do |comment| %>
<section class="comment-name">
  Written by:
<%= comment.name %>
</section>
<p> Posted on <%= comment.created_at.strftime("%m:%d:%Y") %> at <%=comment.created_at.strftime("%T") %></p>
<section class="comment-content">
<%= comment.content %>
</section>
<br />
<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
<%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
<span>&nbsp&nbsp&nbsp</span>
<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
<%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>
<br />
<footer class="page-footer">
<%= link_to "Add a new comment", new_post_comment_path(@post), class: "btn btn-default" %>
<%= link_to "Go back", posts_path, class: "btn btn-default" %>
</footer>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>